# Generated by Django 4.2.25 on 2025-10-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alumniprofile_company_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='apellido_solo',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='apellido (solo)'),
        ),
    ]
