# Generated by Django 4.2.25 on 2025-10-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alumniprofile_apellido_solo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumniprofile',
            options={'ordering': ('apellido_solo', 'user__full_name'), 'verbose_name': 'perfil de exalumno', 'verbose_name_plural': 'perfiles de exalumnos'},
        ),
    ]
